### ISSUE TITLE
preparing for new release e2tools-0.1.0 (as v0.1.0 release tag)

### ISSUE THREAD

**Issue by ncopa** [e2tools/e2tools#1] opened 2020-02-03 10:58 UTC
It would be helpful for downstream packagers with a new release.

Thanks!

**Comment by ndim** [comment] 2020-02-04 19:00
Working on that. @christophgysin and I are joining efforts. I will be merging my stuff from  https://github.com/ndim/e2tools/ into https://github.com/e2tools/e2tools, then there are a few more cleanups to do (make it compile with recent compilers etc.), then we can call the merged release e2tools-0.1.0 and release it.

**Comment by ndim** [comment] 2020-02-05 22:40
Having merged https://github.com/ndim/e2tools/ into https://github.com/e2tools/e2tools and then having fixed and reorganized a few things I have always wanted to do but never could for fear of diverging too far from upstream, I would consider the current state of the https://github.com/e2tools/e2tools source tree master branch ready for release as the first post-merge release `e2tools-0.1.0`.

However, some questions remain:

  * Has anyone notice any oversights on my part regarding the sources? @christophgysin? @ncopa?

  * Then... how will we release? Just a tagged tarball snapshot from git sources generated by the Github releases mechanism, or a "proper" in the GNU sense `make dist` generated tarball on https://e2tools.github.io/? Or both? Or can the `make dist` generated tarball be uploaded to the Github release mechanism somehow? Maybe with Github Actions?

  * And who would prepare that `make dist` tarball on what machine? Github Actions or the maintainer preparing the release?

  * And finally, who would prepare that release? @christophgysin or @ndim? I have no issue with doing that myself, but me having flooded the repo with so many commits in such a short time, I want to avoid steamrollering over everybody else.

Lots of questions, looking for some answers.

**Comment by ndim** [comment] 2020-02-05 23:11
I just found one answer: One can attach "binary" files to Github releases, so uploading the `make dist` generated tarball from the developer's machien to the Github releases mechanism is possible.

**Comment by christophgysin** [comment] 2020-02-06 07:57
Thanks for all the great work!

I would prefer to have as much as possible of the release process automated. How about setting up a Github Action triggered by pushing a signed tag?

**Comment by ndim** [comment] 2020-02-06 10:49
The person doing the release will need to do some manual checking which exceeds what is done on every commit. Otherwise, what is the difference between a release and any other commit?

While I like automation in releases (many of my other projects automatically check that NEWS contains proper release numbers on `make dist`, generates autoconf release numbers from git tags and commits, etc. pp), I have no experience in automating beyond my own machine.

Given my usual luck, other services will have changed something soon so some things differ so much that my automation setup with those other services will fail soon. And a release checklist is required regardless of the amount of automation implemented within the source tree and outside it.

I hate to repeat myself, but... IMHO the complete release automation does not need to be resolved for a quick `e2tools-0.1` release to give distro packagers a contemporary code base to work on.

**Comment by ncopa** [comment] 2020-02-06 13:49
I tested to build it from git master and it had a build error:
```
In file included from e2tool-e2ln.h:4,
                 from e2tools-toolmap.c:5:
/usr/include/ext2fs/ext2fs.h:1360:39: error: unknown type name 'dev_t'; did you mean 'div_t'?
 1360 | extern char *ext2fs_find_block_device(dev_t device);
      |                                       ^~~~~
      |                                       div_t
/usr/include/ext2fs/ext2fs.h:1734:62: error: unknown type name 'mode_t'
 1734 | extern int ext2fs_open_file(const char *pathname, int flags, mode_t mode);
      |                                                              ^~~~~~
```

This is not a problem with e2tools though. Its a problem in e2fsprogs headers, which can be worked around with `CFLAGS+="-DHAVE_SYS_TYPES_H"`.

I don't think this is something e2tools should care about.

Other than that, it builds fine.

> the complete release automation does not need to be resolved for a quick e2tools-0.1 release to give distro packagers a contemporary code base to work on.

totally agree. Thank you for the good work!

**Comment by christophgysin** [comment] 2020-02-06 14:03
I'm not stopping you from making the release manually.

It's good to have a checklist for manual steps. I'm suggesting to automate the steps that can easily be automated, like creating a github release and attaching the dist tarball (if needed). That way, the process is reproducible and documented in code.

Of course, this can be done after a 0.1.0 release.

**Comment by ndim** [comment] 2020-02-06 14:13
@ncopa Just out of curiosity: What kind of system are you building e2tools on, and what version of upstream `ext2fsprogs` is your `ext2fs.h` header from?

FWIW, I have just pushed commit 5e138a3737fcb25615c114eaa15ca36b55e6d75e which includes `e2tools-autoconfig.h` before every `#include` of `ext2fs.h` to work around your issue.

**Comment by ncopa** [comment] 2020-02-06 14:58
@ndim I build on my Alpine Linux (edge) x86_64 desktop, with e2fsprogs-1.45.5.

But i think it is wrong of e2fsprogs to use buildtime autoconf macros in the public header:
```c
#ifdef HAVE_SYS_TYPES_H
#include <sys/types.h>
#endif
```
`dev_t` is also defined in POSIX in [sys/types.h](https://pubs.opengroup.org/onlinepubs/009695399/basedefs/sys/types.h.html) so I think the `#ifdef HAVE_SYS_TYPES_H` should be removed. But again, its not a problem in e2tools.

commit 5e138a3737fcb25615c114eaa15ca36b55e6d75e works around it and works.

Thanks!

**Comment by ndim** [comment] 2020-02-07 03:12
@ncopa I concur that this is a e2fsprogs problem. We will need to take this up with e2fsprogs eventually, but it will take some time before any possible fixes to e2fsprogs make it downstream to everybody.

I am not sure e2tools should depend on the one latest sometime-in-2020 release of e2fsprogs. So this workaround might have to stay in e2tools for a while.

As to why you are running into this while I am not, I presume this is due to me building on a GNU libc system, and your system having musl libc.

**Comment by ndim** [comment] 2020-02-07 09:15
https://github.com/e2tools/e2tools/releases/tag/v0.1.0

**Closed by ndim** 2020-02-07 09:15 UTC
Labels: question
